SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS logs_db;
DROP TABLE IF EXISTS puntajes;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
usuario_id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(80) NOT NULL,
avatar VARCHAR(10) DEFAULT '🎮',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE puntajes (
idPuntajes INT PRIMARY KEY AUTO_INCREMENT,
usuario_id INT NOT NULL,
puntaje INT NOT NULL,
total_preguntas INT DEFAULT 10,
correctas INT NOT NULL,
fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (usuario_id) REFERENCES usuarios(usuario_id)
);

CREATE TABLE logs_db (
idLogs_db INT PRIMARY KEY AUTO_INCREMENT,
usuario_id INT,
accion VARCHAR(50) NOT NULL,
detalle LONGTEXT,
fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (usuario_id) REFERENCES usuarios(usuario_id)
);

SET FOREIGN_KEY_CHECKS=1;
